# Dockerfile
FROM node:22-alpine AS base

WORKDIR /app

COPY . .
# Copy package files first for better caching
# COPY package.json package-lock.json ./

# # Install dependencies at build time
# RUN npm install

# Keep container alive (needed for copying if necessary)
# CMD ["sh", "-c", "while true; do sleep 100; done"]
CMD ["tail", "-f", "/dev/null"]