FROM busybox AS builder
ARG MIMIR_URL
COPY tempo.yaml /etc/tempo.yaml.tmpl
RUN sed "s|MIMIR_URL_PLACEHOLDER|${MIMIR_URL}|g" /etc/tempo.yaml.tmpl > /etc/tempo.yaml

FROM grafana/tempo:2.10.1
COPY --from=builder /etc/tempo.yaml /etc/tempo.yaml
CMD ["-config.file=/etc/tempo.yaml", "-target=all"]
