FROM grafana/tempo:2.10.1

# Copy your config
COPY tempo.yaml /etc/tempo/tempo.yaml

# Explicitly use the flags to enable environment variable expansion
CMD ["-config.file=/etc/tempo/tempo.yaml", "-config.expand-env=true"]