FROM node:22-alpine AS base

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

FROM base AS builder
RUN apk update
RUN apk add --no-cache libc6-compat \
    chromium \
    nss \
    freetype \
    freetype-dev \
    harfbuzz \
    ca-certificates \
    ttf-freefont \
    nodejs \
    postgresql-client

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

WORKDIR /app

RUN corepack enable
RUN npm install turbo --global

WORKDIR /app
COPY . .

RUN turbo prune lv-web --docker

FROM base AS installer
RUN apk update
RUN apk add --no-cache libc6-compat \
    chromium \
    nss \
    freetype \
    freetype-dev \
    harfbuzz \
    ca-certificates \
    ttf-freefont \
    nodejs \
    postgresql-client
WORKDIR /app

RUN corepack enable
COPY --from=builder /app/out/json/ .
RUN npm install --frozen-lockfile

EXPOSE 3000 