import config from '@repo/ui/tailwind.config';
import type { Config } from 'tailwindcss';
import animate from 'tailwindcss-animate';

export default {
  ...config,
  presets: [config],
  darkMode: ['class'],
  prefix: '',
  theme: {
    extend: {
      keyframes: {
        blink: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0' },
        },
      },
      animation: {
        blink: 'blink 1s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
        red: {
          50: 'hsl(var(--alizarin-50))',
          100: 'hsl(var(--alizarin-100))',
          200: 'hsl(var(--alizarin-200))',
          300: 'hsl(var(--alizarin-300))',
          400: 'hsl(var(--alizarin-400))',
          500: 'hsl(var(--alizarin-500))',
          600: 'hsl(var(--alizarin-600))',
          700: 'hsl(var(--alizarin-700))',
          800: 'hsl(var(--alizarin-800))',
          900: 'hsl(var(--alizarin-900))',
          950: 'hsl(var(--alizarin-950))',
        },
        blue: {
          50: 'hsl(var(--ultramarine-50))',
          100: 'hsl(var(--ultramarine-100))',
          200: 'hsl(var(--ultramarine-200))',
          300: 'hsl(var(--ultramarine-300))',
          400: 'hsl(var(--ultramarine-400))',
          500: 'hsl(var(--ultramarine-500))',
          600: 'hsl(var(--ultramarine-600))',
          700: 'hsl(var(--ultramarine-700))',
          800: 'hsl(var(--ultramarine-800))',
          900: 'hsl(var(--ultramarine-900))',
          950: 'hsl(var(--ultramarine-950))',
        },
        green: {
          50: 'hsl(var(--spring-green-50))',
          100: 'hsl(var(--spring-green-100))',
          200: 'hsl(var(--spring-green-200))',
          300: 'hsl(var(--spring-green-300))',
          400: 'hsl(var(--spring-green-400))',
          500: 'hsl(var(--spring-green-500))',
          600: 'hsl(var(--spring-green-600))',
          700: 'hsl(var(--spring-green-700))',
          800: 'hsl(var(--spring-green-800))',
          900: 'hsl(var(--spring-green-900))',
          950: 'hsl(var(--spring-green-950))',
        },
        yellow: {
          50: 'hsl(var(--bright-sun-50))',
          100: 'hsl(var(--bright-sun-100))',
          200: 'hsl(var(--bright-sun-200))',
          300: 'hsl(var(--bright-sun-300))',
          400: 'hsl(var(--bright-sun-400))',
          500: 'hsl(var(--bright-sun-500))',
          600: 'hsl(var(--bright-sun-600))',
          700: 'hsl(var(--bright-sun-700))',
          800: 'hsl(var(--bright-sun-800))',
          900: 'hsl(var(--bright-sun-900))',
          950: 'hsl(var(--bright-sun-950))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      spacing: {
        'scale-70-sm': '36px',
        'scale-70-md': '45px',
        'scale-70': '70px',
        'scale-55-sm': '31.5px',
        'scale-55-md': '37.5px',
        'scale-55': '55px',
        'scale-45-sm': '28.5px',
        'scale-45-md': '32.5px',
        'scale-45': '45px',
        'scale-30-sm': '24px',
        'scale-30-md': '25px',
        'scale-30': '30px',
      },
    },
  },
  plugins: [animate],
} satisfies Config;
