name: Build Docker images (lv-web + lv-pyapi)

on:
  push:
    branches:
      - force-dynamic-bug

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build lv-web image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/lv-web/Dockerfile
          push: false
          tags: lv-web:ci-${{ github.sha }}
          build-args: |
            NEXT_PUBLIC_ENVIRONMENT=dev
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Log lv-web build success
        run: echo "lv-web image succesful!"

      - name: Build lv-pyapi image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/lv-pyapi/Dockerfile
          push: false
          tags: lv-pyapi:ci-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Log pyapi build success
        run: echo "pyapi image successful!"