steps:
  - name: Checkout
    uses: actions/checkout@v2

  - name: Setup Node
    uses: actions/setup-node@v3
    with:
      node-version: '20'

  - name: Install dependencies
    run: npm install --frozen-lockfile

  - name: Create .env file
    run: |
      touch packages/database/.env
      echo "DATABASE_URL=postgresql://${{ secrets.PGUSER }}:${{ secrets.PGPASSWORD }}@127.0.0.1:5432/${{ secrets.DBNAME }}" >> packages/database/.env
      echo "DIRECT_DATABASE_URL=postgresql://${{ secrets.PGUSER }}:${{ secrets.PGPASSWORD }}@127.0.0.1:5432/${{ secrets.DBNAME }}" >> packages/database/.env
      echo "NODE_ENV=development" >> packages/database/.env

  - name: Run migrations
    run: npx turbo run db:deploy

  - name: Generate Prisma client
    run: npx turbo run db:generate

  # - name: Seed database
  #  run: npx turbo run db:seed

  - name: Cleanup
    run: rm packages/database/.env
