name: Test DB Connection (Official Google Setup)

on:
  push:
    branches:
      - test-sql-connection
  workflow_dispatch:

jobs:
  test-connection:
    runs-on: ubuntu-latest

    steps:
      # 1. Tunnistaudu
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 2. Asenna gcloud (virallinen)
      - name: Setup Google Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      # 3. Lataa Cloud SQL Proxy
      - name: Download Cloud SQL Proxy
        run: curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-proxy/v2.11.0/cloud-sql-proxy.linux.amd64

      # 4. Tee suoritettavaksi
      - name: Make Proxy Executable
        run: chmod +x cloud-sql-proxy

      # 5. Käynnistä proxy TAUSTALLE (&-merkki)
      - name: Start Cloud SQL Proxy
        # Käyttää sinun PGHOST-secretiäsi yhteysnimenä
        run: ./cloud-sql-proxy --port 5432 ${{ secrets.PGHOST }} &

      # 6. Testaa yhteys
      - name: Test SQL Connection
        env:
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

          echo "Waiting for proxy to start..."
          sleep 5 # Annetaan proxylle hetki käynnistyä

          echo "Connecting to 127.0.0.1..."
          psql --host 127.0.0.1 \
               --username ${{ secrets.PGUSER }} \
               --dbname ${{ secrets.PGDATABASE }} \
               --command "\dt"

          echo "Connection successful"
