name: Test DB Connection (Service Account)

on:
  push:
    branches:
      - test-sql-connection
  workflow_dispatch:

jobs:
  test-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Start Cloud SQL Proxy
        run: |
          wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
          chmod +x cloud_sql_proxy
          ./cloud_sql_proxy -instances=${{ secrets.PGHOST }}=tcp:5432 &
          sleep 5

      - name: Install psql client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Test Cloud SQL connection
        run: |
          PGPASSWORD=${{ secrets.PGPASSWORD }} psql \
            -h 127.0.0.1 -p 5432 \
            -U ${{ secrets.PGUSER }} \
            -d ${{ secrets.PGDATABASE }} \
            -c "SELECT NOW();"
